### ISSUE TITLE
fileGrp USE="OCR-D-GT-PAGEXML"

### ISSUE THREAD

**Issue by tboenig** [OCR-D/spec#102]
I miss a filegroup for pagexml, especially for ground truth data.
my proposal would be 
``fileGrp USE="OCR-D-GT-PAGEXML``

**Comment by cneud** [comment]
There have always been specific `<fileGrp>` conventions for ground truth in the [spec](https://ocr-d.github.io/mets#file-group-use-syntax), but the first intention was to group these by their *use* rather than format, so we now have e.g. `<mets:fileGrp USE="OCR-D-GT-IMG-BIN">`, `<mets:fileGrp USE="OCR-D-GT-SEG-LINE">` and so forth.

**Comment by kba** [comment]
What @cneud said, plus that the actual format of the ground truth files should be determined by the `MIMETYPE` of the `mets:file`.
