### ISSUE TITLE
allow `object` type parameters in ocrd-tool.json

### ISSUE THREAD

**Issue by bertsky** [OCR-D/spec#143]
Currently, `parameters` are restricted to be either string, number or boolean in the schema for `ocrd-tool.json` files. Why not allow arbitrary `object` as well?

My use-case is: I want to be able to pass a value of (Python-)type `dict`, cf. [colordict here](https://github.com/OCR-D/ocrd_segment/pull/35).

**Comment by kba** [comment]
The intention behind the restriction was to ensure that parameters could be passed easily to processors in different scenarios like command line or services because most serialization formats have primitives like string, number and boolean.

However, since we're using JSON as the serialization throughout at the moment - I have a half-implemented branch with a `-P` to pass invididual parameters but that can wait - I see no reason why parameters couldn't be objects or even arrays.

@VolkerHartmann Would that cause any problems with the Taverna setup?

**Comment by VolkerHartmann** [comment]
This shouldn't be a problem for Taverna as I just pass the parameters to the processors and no additional checks are made.

**Comment by cneud** [comment]
+1 to allow ``object`` as parameter
