### ISSUE TITLE
Media type for PAGE XML?

### ISSUE THREAD

**Issue by kba** [OCR-D/spec#33]
* `text/xml`: Too generic, conflicts likely
* `text/page+xml`: Short and sweet but unofficial
* `text/vnd.ocrd.page+xml`

**Comment by cneud** [comment]
> text/xml: Too generic, conflicts likely

Agreed.

> text/page+xml: Short and sweet but unofficial

Certainly nice, but doing this in the correct way requires submitting a RFC to IANA. We're doing this for ALTO atm, it involves considerable effort.

> text/vnd.ocrd.page+xml

Based on the above, this one has my vote.

**Comment by cneud** [comment]
+1 for `text/vnd.prima.page+xml` but of course want to hear from @PRImA-Research-Lab @chris1010010 @splet first.

**Comment by chris1010010** [comment]
Interesting question. But looking at some examples here:
http://www.iana.org/assignments/media-types/media-types.xhtml

Should it not be "application/...+xml"?

I've never looked into this kind of thing though.

Best,
Christian

**Comment by VolkerHartmann** [comment]
Well, 90% of all entries start with 'application'. I've always 
interpreted it as saying that 'application' is linked to a particular 
application, while page, like html, is just a text format (e.g. like 
image/jpg is an image format). But that doesn't fit with many entries 
either. The question is whether the majority is wrong?

Regards,
   Volker

**Comment by chris1010010** [comment]
There's even a Wikipedia entry on this:

https://en.m.wikipedia.org/wiki/XML_and_MIME

There's one example that's not application+xml: image/svg+xml.

So I would interpret the first bit (text, image, application) as the
semantic interpretation of the file and the second part (html, plain, csv,
+xml) as the technical interpretation.

Now I agree, it's not very clean. Say text/html for example. It's not just
text nowadays.

Since PAGE contains more than text (polygons, structure, reading order,
metadata,...) I would lean more towards "application".

Clemens, ALTO is applying for application/alto+xml?

Best,
Christian

**Comment by kba** [comment]
If IIUC [RFC 6838](https://tools.ietf.org/html/rfc6838#section-4.2.1) I think `text` was actually the right media type, were it not for the restriction "it is reasonable to present subtypes of "text" to the user, while it is not reasonable to do so with most non-textual data.". That's arguably not true for verbose XML like ALTO or PAGE. It is not true for `text/rtf`, `text/xml`, `text/html` etc. either but for consistency, `application` seems the right top-level media type.

ALTO does (will) use `application/alto+xml`: https://github.com/altoxml/board/wiki/The-'application-alto-xml'-Media-Type

So, `application//vnd.prima.page+xml` it is?

**Comment by chris1010010** [comment]
I’d be happy with that.

 

Best,

Christian

**Comment by VolkerHartmann** [comment]
:+1:

**Comment by kba** [comment]
Merged
